In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as sp
import seaborn as sns
from scipy.stats import ttest_ind
from scipy.stats import linregress
from scipy import stats

%matplotlib inline
df = pd.read_csv('/Users/joshuarkarnad/Desktop/Thinkful/Data/NFL Play by Play 2009-2016 (v3).csv')

/Users/joshuarkarnad/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [2]:
nfl2009 = df[df['Season'] == 2009]
nfl2010 = df[df['Season'] == 2010]
defavg = nfl2009[['DefensiveTeam', 'Yards.Gained']].groupby('DefensiveTeam').agg(np.mean).reset_index()
defavg.columns=['posteam', 'DefRating']
offavg = nfl2009[['posteam', 'Yards.Gained']].groupby('posteam').agg(np.mean).reset_index()
offavg.columns=['posteam', 'OffRating']
nfl2010 = offavg.merge(nfl2010, on = 'posteam', how = 'left')
nfl2010 = defavg.merge(nfl2010, on = 'posteam', how = 'left')

In [3]:
nfl2010.head()

posteam  DefRating  OffRating        Date      GameID  Drive  qtr  down  \
0     ARI   5.518657   5.861989  2010-09-12  2010091208      1    1   NaN   
1     ARI   5.518657   5.861989  2010-09-12  2010091208      1    1   1.0   
2     ARI   5.518657   5.861989  2010-09-12  2010091208      1    1   2.0   
3     ARI   5.518657   5.861989  2010-09-12  2010091208      1    1   3.0   
4     ARI   5.518657   5.861989  2010-09-12  2010091208      1    1   1.0   

    time  TimeUnder  ...      yacEPA  Home_WP_pre Away_WP_pre  Home_WP_post  \
0  15:00         15  ...         NaN     0.514325    0.485675      0.508230   
1  14:55         15  ...    0.000000     0.508230    0.491770      0.528762   
2  14:24         15  ...         NaN     0.528762    0.471238      0.528236   
3  13:43         14  ...    0.912915     0.528236    0.471764      0.439969   
4  13:17         14  ...    1.724125     0.439969    0.560031      0.403268   

   Away_WP_post  Win_Prob       WPA    airWPA    yacWPA Season  
0      0.491770  0.485675  0.006095       NaN       NaN   2010  
1      0.471238  0.491770 -0.020531 -0.020531  0.000000   2010  
2      0.471764  0.471238  0.000525       NaN       NaN   2010  
3      0.560031  0.471764  0.088268  0.058835  0.029432   2010  
4      0.596732  0.560031  0.036701 -0.019847  0.056548   2010  

[5 rows x 104 columns]

In [4]:
nfl2010['Number_Plays_for_TD'] = ((nfl2010.yrdline100) / (nfl2010.OffRating))

In [5]:
nfl2010.head().T

0  \
posteam                                                                    ARI   
DefRating                                                              5.51866   
OffRating                                                              5.86199   
Date                                                                2010-09-12   
GameID                                                              2010091208   
Drive                                                                        1   
qtr                                                                          1   
down                                                                       NaN   
time                                                                     15:00   
TimeUnder                                                                   15   
TimeSecs                                                                  3600   
PlayTimeDiff                                                                 0   
SideofField                                                                STL   
yrdln                                                                       30   
yrdline100                                                                  30   
ydstogo                                                                      0   
ydsnet                                                                       0   
GoalToGo                                                                     0   
FirstDown                                                                  NaN   
DefensiveTeam                                                              STL   
desc                         Josh.Brown kicks 70 yards from SL 30 to ARI 0....   
PlayAttempted                                                                1   
Yards.Gained                                                                22   
sp                                                                           0   
Touchdown                                                                    0   
ExPointResult                                                              NaN   
TwoPointConv                                                               NaN   
DefTwoPoint                                                                NaN   
Safety                                                                       0   
Onsidekick                                                                   0   
...                                                                        ...   
Timeout_Indicator                                                            0   
Timeout_Team                                                              None   
posteam_timeouts_pre                                                         3   
HomeTimeouts_Remaining_Pre                                                   3   
AwayTimeouts_Remaining_Pre                                                   3   
HomeTimeouts_Remaining_Post                                                  3   
AwayTimeouts_Remaining_Post                                                  3   
No_Score_Prob                                                       0.00150633   
Opp_Field_Goal_Prob                                                   0.179749   
Opp_Safety_Prob                                                     0.00663911   
Opp_Touchdown_Prob                                                    0.281138   
Field_Goal_Prob                                                         0.2137   
Safety_Prob                                                         0.00359231   
Touchdown_Prob                                                        0.313676   
ExPoint_Prob                                                                 0   
TwoPoint_Prob                                                                0   
ExpPts                                                                0.323526   
EPA                                                        

In [8]:
nfl2010['Urgency'] =  nfl2010.ScoreDiff / nfl2010.TimeSecs
nfl2010['Avg_Needed_For_1st'] = nfl2010['ydstogo'] / (5 - nfl2010['down'])


In [9]:
print('\n'.join(list(nfl2010.columns)))

posteam
DefRating
OffRating
DefRating_x
OffRating_x
DefRating_y
OffRating_y
Date
GameID
Drive
qtr
down
time
TimeUnder
TimeSecs
PlayTimeDiff
SideofField
yrdln
yrdline100
ydstogo
ydsnet
GoalToGo
FirstDown
DefensiveTeam
desc
PlayAttempted
Yards.Gained
sp
Touchdown
ExPointResult
TwoPointConv
DefTwoPoint
Safety
Onsidekick
PuntResult
PlayType
Passer
Passer_ID
PassAttempt
PassOutcome
PassLength
AirYards
YardsAfterCatch
QBHit
PassLocation
InterceptionThrown
Interceptor
Rusher
Rusher_ID
RushAttempt
RunLocation
RunGap
Receiver
Receiver_ID
Reception
ReturnResult
Returner
BlockingPlayer
Tackler1
Tackler2
FieldGoalResult
FieldGoalDistance
Fumble
RecFumbTeam
RecFumbPlayer
Sack
Challenge.Replay
ChalReplayResult
Accepted.Penalty
PenalizedTeam
PenaltyType
PenalizedPlayer
Penalty.Yards
PosTeamScore
DefTeamScore
ScoreDiff
AbsScoreDiff
HomeTeam
AwayTeam
Timeout_Indicator
Timeout_Team
posteam_timeouts_pre
HomeTimeouts_Remaining_Pre
AwayTimeouts_Remaining_Pre
HomeTimeouts_Remaining_Post
AwayTimeouts_Remaini

In [14]:
df = nfl2010[]
df.isnull().sum().sort_values(ascending=False)

DefTwoPoint                    41961
BlockingPlayer                 41949
TwoPointConv                   41907
ChalReplayResult               41621
Interceptor                    41417
RecFumbPlayer                  41408
RecFumbTeam                    41408
FieldGoalDistance              40996
FieldGoalResult                40976
ExPointResult                  40832
ReturnResult                   40685
PenaltyType                    40227
PuntResult                     39456
PenalizedPlayer                38981
PenalizedTeam                  38865
Returner                       38523
Tackler2                       35784
RunGap                         32199
RunLocation                    28535
Rusher                         28412
yacWPA                         24787
airWPA                         24765
yacEPA                         24758
airEPA                         24750
Receiver                       24656
PassLength                     24000
PassLocation                   24000
P

In [25]:
df = nfl2010[['down', 'Yards.Gained', 'PlayType', 'TimeSecs', 'ydstogo', 'FirstDown']]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [34]:
nfl2010['Fumble']

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        1
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
41931    0
41932    0
41933    0
41934    0
41935    0
41936    0
41937    0
41938    0
41939    0
41940    0
41941    1
41942    0
41943    0
41944    0
41945    0
41946    1
41947    0
41948    1
41949    0
41950    0
41951    0
41952    0
41953    0
41954    0
41955    0
41956    0
41957    0
41958    0
41959    0
41960    0
Name: Fumble, Length: 41961, dtype: int64

In [26]:
dfruns = df[df['PlayType'] == 'Run']
dfpass = df[df['PlayType'] == 'Run']

In [107]:
dftest = pd.concat([dfruns, dfpass])

In [28]:
dftest.head()

down  Yards.Gained PlayType  TimeSecs  ydstogo
2    2.0             5      Run    3564.0       10
5    1.0             2      Run    3472.0       10
7    1.0             2      Run    3401.0       10
8    2.0             1      Run    3363.0        8
13   1.0            -1      Run    3087.0       10

In [29]:
dftest.isnull().sum()

down            28
Yards.Gained     0
PlayType         0
TimeSecs         0
ydstogo          0
dtype: int64

In [31]:
dftest = dftest.dropna()

In [32]:
len(dftest)

27164

Pass          3435
Run           2709
No Play        471
Punt           462
Sack           227
Field Goal     198
QB Kneel        72
Spike           14
Name: PlayType, dtype: int64

In [111]:
dfrunpass = df2[df2.PlayType.isin(['Run', 'Pass'])]
dfrunpass.PlayType.value_counts()

Pass    3435
Run     2709
Name: PlayType, dtype: int64

In [98]:
x.head()

down  TimeSecs  ydstogo  PlayType_Field Goal  PlayType_No Play  \
25800   2.0    2369.0       10                    0                 0   
32737   2.0    1447.0        2                    0                 0   
9136    1.0    2857.0       10                    0                 0   
36584   2.0    2651.0       10                    0                 0   
2524    2.0    1005.0        3                    0                 0   

       PlayType_Pass  PlayType_Punt  PlayType_QB Kneel  PlayType_Run  \
25800              0              0                  0             1   
32737              0              0                  0             1   
9136               0              0                  0             1   
36584              1              0                  0             0   
2524               0              0                  0             0   

       PlayType_Sack  PlayType_Spike  
25800              0               0  
32737              0               0  
9136               0               0  
36584              0               0  
2524               1               0

In [99]:
from sklearn.neural_network import MLPRegressor
df2.isnull().sum()

down            0
Yards.Gained    0
PlayType        0
TimeSecs        0
ydstogo         0
dtype: int64

In [100]:
mlp = MLPRegressor(hidden_layer_sizes=(100,25))
mlp.fit(x,y)

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 25), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [101]:
mlp.score(x,y)

0.047360171910218352

In [102]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, x, y, cv=5)

array([ 0.02317582, -0.20332097, -0.07185759, -0.005482  , -0.0048085 ])

In [103]:
mlp  ==  MLPRegressor(hidden_layer_sizes=(100,50,25,10 ), alpha=0.001)
mlp.fit(x, y)
print(mlp.score(x, y))
MLP_score = cross_val_score(mlp, x, y, cv=5)
print('\nEach Cross Validated Accuracy: \n', MLP_score)
print("\nOverall Neural Network Classifier Accuracy: %0.2f (+/- %0.2f)\n" % (MLP_score.mean(), MLP_score.std() * 2))

-0.0357932425963

Each Cross Validated Accuracy: 
 [ 0.05097345 -0.12508394  0.04478366 -0.05553957 -0.00041143]

Overall Neural Network Classifier Accuracy: -0.02 (+/- 0.13)



In [124]:
mlp  =  MLPClassifier(hidden_layer_sizes=(100,50,25 ), alpha=0.001, solver = 'lbfgs')
mlp.fit(x, y)
print(mlp.score(x, y))
MLP_score = cross_val_score(mlp, x, y, cv=5)
print('\nEach Cross Validated Accuracy: \n', MLP_score)
print("\nOverall Neural Network Classifier Accuracy: %0.2f (+/- %0.2f)\n" % (MLP_score.mean(), MLP_score.std() * 2))

0.51513671875

Each Cross Validated Accuracy: 
 [ 0.59886086  0.61757526  0.57282343  0.57851912  0.56188925]

Overall Neural Network Classifier Accuracy: 0.59 (+/- 0.04)



In [72]:
from sklearn.model_selection import GridSearchCV

In [73]:
from sklearn.ensemble import RandomForestClassifier

In [74]:
param_search = [{'n_estimators': [2,3,5,10,15,20,100,200],
          'max_depth': [3,4,5,6,8,10,15],
          'min_samples_split':[2,3,5,6,8,10,15,20]}]


rfc_grid = GridSearchCV(RandomForestClassifier(), param_grid=param_search,cv=5)

rfc_grid.fit(x,y)

print('Best Score: ', rfc_grid.best_score_)
print('Best Parameters: ', rfc_grid.best_params_)

/Users/joshuarkarnad/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


Best Score:  0.34849286092
Best Parameters:  {'max_depth': 6, 'min_samples_split': 15, 'n_estimators': 5}


In [117]:
from sklearn.ensemble import RandomForestRegressor
rfc = RandomForestClassifier()
rfc.fit(x, y)
rfc.score(x, y)

0.96875

In [118]:
RFC_score = cross_val_score(rfc, x, y, cv=5)
print('\nEach Cross Validated Accuracy: \n', RFC_score)
print("\nOverall Random Forest Classifier Accuracy: %0.2f (+/- %0.2f)\n" % (RFC_score.mean(), RFC_score.std() * 2))


Each Cross Validated Accuracy: 
 [ 0.70626526  0.72416599  0.70626526  0.71277461  0.70439739]

Overall Random Forest Classifier Accuracy: 0.71 (+/- 0.01)



In [115]:
x_vars = ['down', 'Yards.Gained', 'TimeSecs', 'ydstogo']
dfrunpass = dfrunpass.dropna()
x = dfrunpass[x_vars]
x = pd.get_dummies(x)
y = dfrunpass['PlayType'] == 'Run'
y = y.astype(int)

In [116]:
y.head()

25800    1
32737    1
9136     1
36584    0
21869    1
Name: PlayType, dtype: int64